import React from 'react';
import { Link } from 'react-router-dom';
import Navbar from '../components/Navbar';

const features = [
  { icon: '📱', title: 'Social Media Posts', desc: 'LinkedIn, Instagram & Facebook copy tailored to your brand voice and audience.' },
  { icon: '💬', title: 'WhatsApp Broadcasts', desc: 'Conversational messages your customers actually read and respond to.' },
  { icon: '🎯', title: 'Google & Meta Ads', desc: 'High-converting ad headlines, descriptions and CTAs — ready to paste.' },
  { icon: '📧', title: 'Email Campaigns', desc: 'Subject lines and email body copy that drives opens and clicks.' },
];

const steps = [
  { n: '1', title: 'Describe your business', desc: 'Enter your business type, product, and target audience.' },
  { n: '2', title: 'Choose your language', desc: 'Generate in 50+ languages for any market worldwide.' },
  { n: '3', title: 'Get all content instantly', desc: 'Social, WhatsApp, ads and email — all in one click.' },
];

export default function Landing({ session }) {
  return (
    <div>
      <Navbar session={session} />

      {/* Hero */}
      <section style={{ background: 'linear-gradient(135deg, #eef2ff 0%, #f8fafc 60%)', padding: '5rem 1.5rem 4rem' }}>
        <div className="container" style={{ textAlign: 'center' }}>
          <div className="badge badge-starter" style={{ marginBottom: '1rem' }}>✦ AI-Powered Marketing</div>
          <h1 style={{ fontSize: 'clamp(2rem, 5vw, 3.2rem)', fontWeight: 800, lineHeight: 1.2, marginBottom: '1.2rem' }}>
            Generate your entire<br />
            <span style={{ color: '#6366f1' }}>marketing content</span> in seconds
          </h1>
          <p style={{ fontSize: '1.15rem', color: '#64748b', maxWidth: 520, margin: '0 auto 2rem' }}>
            Social posts, WhatsApp messages, ad copy and email campaigns — all generated by AI for your business, in any language, for any market.
          </p>
          <div style={{ display: 'flex', gap: '1rem', justifyContent: 'center', flexWrap: 'wrap' }}>
            <Link to="/signup" className="btn btn-primary" style={{ fontSize: '1rem', padding: '0.8rem 2rem' }}>
              Start free — no credit card
            </Link>
            <Link to="/pricing" className="btn btn-secondary" style={{ fontSize: '1rem', padding: '0.8rem 2rem' }}>
              View pricing
            </Link>
          </div>
          <p style={{ marginTop: '1rem', fontSize: '0.85rem', color: '#94a3b8' }}>
            5 free generations/month · No credit card · Works in 50+ languages
          </p>
        </div>
      </section>

      {/* Features */}
      <section style={{ padding: '4rem 1.5rem' }}>
        <div className="container">
          <h2 style={{ textAlign: 'center', fontSize: '1.8rem', fontWeight: 800, marginBottom: '0.5rem' }}>Everything your marketing needs</h2>
          <p style={{ textAlign: 'center', color: '#64748b', marginBottom: '2.5rem' }}>Four channels. One click. Done.</p>
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(230px, 1fr))', gap: '1.2rem' }}>
            {features.map(f => (
              <div key={f.title} className="card" style={{ textAlign: 'center' }}>
                <div style={{ fontSize: '2.2rem', marginBottom: '0.8rem' }}>{f.icon}</div>
                <h3 style={{ fontWeight: 700, marginBottom: '0.5rem' }}>{f.title}</h3>
                <p style={{ color: '#64748b', fontSize: '0.9rem' }}>{f.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* How it works */}
      <section style={{ background: '#f8fafc', padding: '4rem 1.5rem' }}>
        <div className="container">
          <h2 style={{ textAlign: 'center', fontSize: '1.8rem', fontWeight: 800, marginBottom: '2.5rem' }}>How it works</h2>
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))', gap: '1.5rem', maxWidth: 700, margin: '0 auto' }}>
            {steps.map(s => (
              <div key={s.n} style={{ textAlign: 'center' }}>
                <div style={{ width: 48, height: 48, borderRadius: '50%', background: '#6366f1', color: '#fff', fontWeight: 800, fontSize: '1.2rem', display: 'flex', alignItems: 'center', justifyContent: 'center', margin: '0 auto 1rem' }}>{s.n}</div>
                <h3 style={{ fontWeight: 700, marginBottom: '0.4rem' }}>{s.title}</h3>
                <p style={{ color: '#64748b', fontSize: '0.9rem' }}>{s.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA */}
      <section style={{ padding: '4rem 1.5rem', textAlign: 'center' }}>
        <div className="container">
          <h2 style={{ fontSize: '1.8rem', fontWeight: 800, marginBottom: '1rem' }}>Ready to grow your business?</h2>
          <p style={{ color: '#64748b', marginBottom: '2rem' }}>Join thousands of businesses using MarketAI to automate their marketing.</p>
          <Link to="/signup" className="btn btn-primary" style={{ fontSize: '1rem', padding: '0.8rem 2.5rem' }}>
            Get started free today
          </Link>
        </div>
      </section>

      {/* Footer */}
      <footer style={{ background: '#1e293b', color: '#94a3b8', textAlign: 'center', padding: '1.5rem', fontSize: '0.85rem' }}>
        © 2026 MarketAI Global · AI-powered marketing for businesses worldwide
      </footer>
    </div>
  );
}
