import React from 'react';
import Navbar from '../components/Navbar';

export default function Terms({ session }) {
  return (
    <div>
      <Navbar session={session} />
      <div style={{ maxWidth: 800, margin: '0 auto', padding: '3rem 1.5rem' }}>
        <h1 style={{ fontSize: '2rem', fontWeight: 800, marginBottom: '0.5rem' }}>Terms & Conditions</h1>
        <p style={{ color: '#64748b', marginBottom: '2rem' }}>Last updated: June 15, 2026</p>

        {[
          {
            title: '1. Acceptance of Terms',
            content: `By accessing and using MarketAI Global ("Service"), you accept and agree to be bound by these Terms and Conditions. If you do not agree to these terms, please do not use our Service. These terms apply to all visitors, users, and others who access or use the Service.`
          },
          {
            title: '2. Description of Service',
            content: `MarketAI Global is an AI-powered digital marketing content generation platform. Our Service allows users to generate marketing content including social media posts, WhatsApp messages, Google/Meta ad copy, and email campaigns using artificial intelligence. The Service is provided on a subscription basis with free and paid tiers.`
          },
          {
            title: '3. User Accounts',
            content: `To use our Service, you must create an account. You are responsible for:
• Maintaining the confidentiality of your account credentials
• All activities that occur under your account
• Providing accurate and complete information during registration
• Notifying us immediately of any unauthorized use of your account

We reserve the right to terminate accounts that violate these terms.`
          },
          {
            title: '4. Subscription Plans and Payments',
            content: `MarketAI Global offers the following plans:
• Free Plan: 5 generations per month at no cost
• Starter Plan: 100 generations per month at ₹999/month (INR) or $19/month (USD)
• Pro Plan: Unlimited generations at ₹2,499/month (INR) or $49/month (USD)

Payments are processed securely through Razorpay (for INR payments) and Infinity (for USD payments). Subscriptions automatically renew monthly unless cancelled. Prices are subject to change with 30 days notice.`
          },
          {
            title: '5. Acceptable Use',
            content: `You agree not to use our Service to:
• Generate content that is illegal, harmful, threatening, abusive, or defamatory
• Violate any applicable laws or regulations
• Infringe on intellectual property rights of others
• Generate spam or unsolicited marketing content
• Attempt to reverse engineer or compromise our AI systems
• Share your account credentials with others
• Resell our Service without written permission

We reserve the right to suspend or terminate accounts that violate these guidelines.`
          },
          {
            title: '6. AI-Generated Content',
            content: `You understand and agree that:
• Content generated by our AI is based on your inputs and may not always be accurate
• You are solely responsible for reviewing and editing AI-generated content before use
• We do not guarantee that AI-generated content will be free from errors or suitable for your specific needs
• You own the rights to content generated using our Service
• We may use anonymized usage data to improve our AI models`
          },
          {
            title: '7. Intellectual Property',
            content: `The Service and its original content, features, and functionality are owned by MarketAI Global and are protected by international copyright, trademark, patent, trade secret, and other intellectual property laws. You may not copy, modify, distribute, or create derivative works based on our Service without our explicit written permission.`
          },
          {
            title: '8. Limitation of Liability',
            content: `To the maximum extent permitted by law, MarketAI Global shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including loss of profits, data, or goodwill, arising from your use of the Service. Our total liability for any claims arising from these terms shall not exceed the amount paid by you to us in the past 12 months.`
          },
          {
            title: '9. Disclaimer of Warranties',
            content: `The Service is provided on an "AS IS" and "AS AVAILABLE" basis without any warranties of any kind, either express or implied. We do not warrant that the Service will be uninterrupted, error-free, or free of viruses or other harmful components. We do not guarantee the accuracy or completeness of any AI-generated content.`
          },
          {
            title: '10. Governing Law',
            content: `These Terms shall be governed by and construed in accordance with the laws of India. Any disputes arising under these terms shall be subject to the exclusive jurisdiction of the courts located in Rajasthan, India.`
          },
          {
            title: '11. Changes to Terms',
            content: `We reserve the right to modify these terms at any time. We will notify users of significant changes via email or a prominent notice on our website. Continued use of the Service after changes constitutes acceptance of the new terms.`
          },
          {
            title: '12. Contact Us',
            content: `For any questions about these Terms, please contact us at:\n\nMarketAI Global\nEmail: marketai.global@gmail.com\nWebsite: https://marketai-global.vercel.app`
          },
        ].map(section => (
          <div key={section.title} style={{ marginBottom: '2rem' }}>
            <h2 style={{ fontSize: '1.15rem', fontWeight: 700, marginBottom: '0.7rem', color: '#1e293b' }}>{section.title}</h2>
            <p style={{ color: '#475569', lineHeight: 1.8, whiteSpace: 'pre-line' }}>{section.content}</p>
          </div>
        ))}
      </div>
    </div>
  );
}
